# This pipeline uses maven and docker to build, test and package spring boot application.
name: Java CI with Maven

# Trigger when pushed to main branch or pull requests are opened for main branch
on:
  push:
    branches: [ "main", "experiment" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # use mac-os VM to run the job
    runs-on: macos-latest

    steps:
    # checkout repository
    - uses: actions/checkout@v3

    # install jdk 17 with maven
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # use maven to build and test the application
    - name: Build with Maven
      run: mvn -e -B package --file demo-spring/pom.xml

    # Install docker on macOS
    - name: Setup Docker on macOS
      uses: douglascamata/setup-docker-macos-action@v1-alpha

    # Log into docker hub using username and token
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Install buildx to build docker images
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    # Run docker build and docker push
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: achalk/demo-spring:latest
